### ISSUE TITLE
Tuner spelled as Tunner

### ISSUE THREAD

**Issue by AvdWerfhorst** [elvenpath/CambridgeAudioAzur351R-RS232toMqtt#2]
Thank you for your awesome component. I use it with Home Assistant to automatically switch on (and up in the right mode) while I switch on my TV, or stream something to my Chromecast Audio. This works so much faster (and more stable) than the IR way.

The only minor thing that I see as a down side, is that you spelled "Tunner" instead of "Tuner". Fix that and I am totally happy.

**Comment by elvenpath** [comment]
I'll have a new version published soon with some minor improvements, I promise I'll correct that :)

**Comment by elvenpath** [comment]
https://github.com/elvenpath/CambridgeAudioAzur351R-RS232toMqtt/releases/tag/v1.20
